### ISSUE TITLE
Bedrock issues

### ISSUE THREAD

**Issue by Sanderbloem050** [kobenetwork/alysaa#8]
He there, if joined a couple of times now some thru java (worked perfectly) also with bedrock ps4. If I'm on with ps4 there are some strange things happening. Like making a pick but when clicking the pick in the menu it glitches a few times until I got kicked out cause of to many packets.. also it seems a bit different with ps4 regarding to texture packs and such..

**Comment by kobenetwork** [comment]
Disabled ban on sending to many packages.
